UI Gh-76, 111, 109, 112, 118 and 121
gchq/gaffer-experimental pull request #130
Opened 2021-07-09 12:47 UTC by rocky341

Ui release for the following tickets:
#76 #111 #109 #112 #118 #121

2021-08-04 10:21 UTC, t92549 requested changes

2021-08-04 10:21 UTC, t92549 commented on gaas-ui/src/components/cluster-namespaces/cluster-namespaces.tsx
> +                        <Copyright />
This could maybe be on all pages?

2021-08-04 15:32 UTC, rocky341 commented on gaas-ui/src/components/cluster-namespaces/cluster-namespaces.tsx
> +                        <Copyright />
Done

2021-08-04 15:40 UTC, rocky341 commented on gaas-ui/.eslintrc.json
> -    "no-invalid-this": "error",
Taking a look into this. Adding the rule back breaks `src/rest/clients/rest-client.ts` but everything else seems ok. I'll get back to you on this.

2021-08-05 11:41 UTC, rocky341 commented on gaas-ui/.eslintrc.json
> -    "no-invalid-this": "error",
@t92549 
Rule has been added back in. RestClient has been modified slightly in order to comply to this new rule.

2021-08-05 13:18 UTC, t92549 approved these changes

2021-08-05 13:19 UTC, merged